// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAICopilot(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AskAICopilot'](arg1, arg2, arg3, arg4, arg5);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function GetActiveTunnels() {
  return window['go']['main']['App']['GetActiveTunnels']();
}

export function GetHosts() {
  return window['go']['main']['App']['GetHosts']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveHost(arg1) {
  return window['go']['main']['App']['SaveHost'](arg1);
}

export function SendTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalInput'](arg1, arg2);
}

export function StartLocalTerminal(arg1, arg2) {
  return window['go']['main']['App']['StartLocalTerminal'](arg1, arg2);
}

export function StartPortForward(arg1, arg2) {
  return window['go']['main']['App']['StartPortForward'](arg1, arg2);
}

export function StartSSHTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSSHTerminal'](arg1, arg2, arg3);
}

export function StopPortForward(arg1) {
  return window['go']['main']['App']['StopPortForward'](arg1);
}
