// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {discovery} from '../models';
import {models} from '../models';
import {services} from '../models';
import {plugins} from '../models';
import {importers} from '../models';
import {ssh} from '../models';
import {gitops} from '../models';
import {diagnostics} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateRemoteFolder(arg1:string,arg2:string):Promise<void>;

export function DeleteHost(arg1:string):Promise<void>;

export function DeleteRemoteFile(arg1:string,arg2:string):Promise<void>;

export function DeleteSnippet(arg1:string):Promise<void>;

export function DetectSystemTools():Promise<Array<discovery.DetectedTool>>;

export function DiscoverAllResources():Promise<Array<models.Resource>>;

export function DiscoverDockerContainers():Promise<Array<discovery.DockerContainerInfo>>;

export function DiscoverSSHConfig():Promise<Array<models.Host>>;

export function DockerGetLogs(arg1:string,arg2:number):Promise<string>;

export function DockerRemoveContainer(arg1:string):Promise<void>;

export function DockerRestartContainer(arg1:string):Promise<void>;

export function DockerStartContainer(arg1:string):Promise<void>;

export function DockerStopContainer(arg1:string):Promise<void>;

export function ExecuteResourceAction(arg1:models.ActionPayload):Promise<models.ActionResult>;

export function GetActiveRemoteServices():Promise<Array<services.ActiveServiceStatus>>;

export function GetActiveSessions():Promise<Array<models.Session>>;

export function GetActiveTunnels():Promise<Array<models.PortForwardRule>>;

export function GetGitOpsConfig():Promise<models.GitOpsConfig>;

export function GetHosts():Promise<Array<models.Host>>;

export function GetInstalledPlugins():Promise<Array<plugins.PluginManifest>>;

export function GetKnownHosts():Promise<Array<models.KnownHostRecord>>;

export function GetSnippets():Promise<Array<models.Snippet>>;

export function GetUnifiedInfrastructureTree():Promise<Array<models.InfrastructureNode>>;

export function ImportMobaXterm(arg1:string):Promise<importers.ImportResult>;

export function ImportTermiusJSON(arg1:string):Promise<importers.ImportResult>;

export function LaunchRemoteIDE(arg1:string,arg2:string,arg3:string):Promise<void>;

export function LaunchRemoteService(arg1:string,arg2:models.RemoteService):Promise<services.ActiveServiceStatus>;

export function ListRemoteFiles(arg1:string,arg2:string):Promise<Array<ssh.RemoteFileInfo>>;

export function ReadRemoteFile(arg1:string,arg2:string):Promise<string>;

export function RefreshDiscovery():Promise<Array<models.ProviderDiscoveryResult>>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveGitOpsConfig(arg1:models.GitOpsConfig):Promise<void>;

export function SaveHost(arg1:models.Host):Promise<void>;

export function SaveSnippet(arg1:models.Snippet):Promise<void>;

export function ScanSubnet(arg1:string,arg2:Array<number>):Promise<Array<models.DiscoveredDevice>>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<void>;

export function SetResourceAlias(arg1:string,arg2:string):Promise<void>;

export function StartConnectionTerminal(arg1:models.Connection,arg2:number,arg3:number):Promise<string>;

export function StartDockerTerminal(arg1:string,arg2:number,arg3:number):Promise<string>;

export function StartLocalTerminal(arg1:number,arg2:number):Promise<string>;

export function StartPortForward(arg1:string,arg2:models.PortForwardRule):Promise<void>;

export function StartSSHTerminal(arg1:string,arg2:number,arg3:number):Promise<string>;

export function StopPortForward(arg1:string):Promise<void>;

export function StopRemoteService(arg1:string):Promise<void>;

export function SyncGitOps():Promise<gitops.SyncResult>;

export function TestDiagnosticsDNS(arg1:string):Promise<diagnostics.DiagnosticsResult>;

export function TestDiagnosticsTCP(arg1:string,arg2:number):Promise<diagnostics.DiagnosticsResult>;

export function TogglePlugin(arg1:string,arg2:boolean):Promise<void>;

export function ToggleResourceFavorite(arg1:string):Promise<boolean>;

export function TriggerBackgroundRefresh():Promise<void>;

export function UploadRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;
