// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreateRemoteFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateRemoteFolder'](arg1, arg2);
}

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function DeleteRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteRemoteFile'](arg1, arg2);
}

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function DetectSystemTools() {
  return window['go']['main']['App']['DetectSystemTools']();
}

export function DiscoverAllResources() {
  return window['go']['main']['App']['DiscoverAllResources']();
}

export function DiscoverDockerContainers() {
  return window['go']['main']['App']['DiscoverDockerContainers']();
}

export function DiscoverSSHConfig() {
  return window['go']['main']['App']['DiscoverSSHConfig']();
}

export function DockerGetLogs(arg1, arg2) {
  return window['go']['main']['App']['DockerGetLogs'](arg1, arg2);
}

export function DockerRemoveContainer(arg1) {
  return window['go']['main']['App']['DockerRemoveContainer'](arg1);
}

export function DockerRestartContainer(arg1) {
  return window['go']['main']['App']['DockerRestartContainer'](arg1);
}

export function DockerStartContainer(arg1) {
  return window['go']['main']['App']['DockerStartContainer'](arg1);
}

export function DockerStopContainer(arg1) {
  return window['go']['main']['App']['DockerStopContainer'](arg1);
}

export function ExecuteResourceAction(arg1) {
  return window['go']['main']['App']['ExecuteResourceAction'](arg1);
}

export function GetActiveRemoteServices() {
  return window['go']['main']['App']['GetActiveRemoteServices']();
}

export function GetActiveSessions() {
  return window['go']['main']['App']['GetActiveSessions']();
}

export function GetActiveTunnels() {
  return window['go']['main']['App']['GetActiveTunnels']();
}

export function GetGitOpsConfig() {
  return window['go']['main']['App']['GetGitOpsConfig']();
}

export function GetHosts() {
  return window['go']['main']['App']['GetHosts']();
}

export function GetInstalledPlugins() {
  return window['go']['main']['App']['GetInstalledPlugins']();
}

export function GetKnownHosts() {
  return window['go']['main']['App']['GetKnownHosts']();
}

export function GetSnippets() {
  return window['go']['main']['App']['GetSnippets']();
}

export function GetUnifiedInfrastructureTree() {
  return window['go']['main']['App']['GetUnifiedInfrastructureTree']();
}

export function ImportMobaXterm(arg1) {
  return window['go']['main']['App']['ImportMobaXterm'](arg1);
}

export function ImportTermiusJSON(arg1) {
  return window['go']['main']['App']['ImportTermiusJSON'](arg1);
}

export function LaunchRemoteIDE(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchRemoteIDE'](arg1, arg2, arg3);
}

export function LaunchRemoteService(arg1, arg2) {
  return window['go']['main']['App']['LaunchRemoteService'](arg1, arg2);
}

export function ListRemoteFiles(arg1, arg2) {
  return window['go']['main']['App']['ListRemoteFiles'](arg1, arg2);
}

export function ReadRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['ReadRemoteFile'](arg1, arg2);
}

export function RefreshDiscovery() {
  return window['go']['main']['App']['RefreshDiscovery']();
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveGitOpsConfig(arg1) {
  return window['go']['main']['App']['SaveGitOpsConfig'](arg1);
}

export function SaveHost(arg1) {
  return window['go']['main']['App']['SaveHost'](arg1);
}

export function SaveSnippet(arg1) {
  return window['go']['main']['App']['SaveSnippet'](arg1);
}

export function ScanSubnet(arg1, arg2) {
  return window['go']['main']['App']['ScanSubnet'](arg1, arg2);
}

export function SendTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalInput'](arg1, arg2);
}

export function SetResourceAlias(arg1, arg2) {
  return window['go']['main']['App']['SetResourceAlias'](arg1, arg2);
}

export function StartConnectionTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartConnectionTerminal'](arg1, arg2, arg3);
}

export function StartDockerTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartDockerTerminal'](arg1, arg2, arg3);
}

export function StartLocalTerminal(arg1, arg2) {
  return window['go']['main']['App']['StartLocalTerminal'](arg1, arg2);
}

export function StartPortForward(arg1, arg2) {
  return window['go']['main']['App']['StartPortForward'](arg1, arg2);
}

export function StartSSHTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSSHTerminal'](arg1, arg2, arg3);
}

export function StopPortForward(arg1) {
  return window['go']['main']['App']['StopPortForward'](arg1);
}

export function StopRemoteService(arg1) {
  return window['go']['main']['App']['StopRemoteService'](arg1);
}

export function SyncGitOps() {
  return window['go']['main']['App']['SyncGitOps']();
}

export function TestDiagnosticsDNS(arg1) {
  return window['go']['main']['App']['TestDiagnosticsDNS'](arg1);
}

export function TestDiagnosticsTCP(arg1, arg2) {
  return window['go']['main']['App']['TestDiagnosticsTCP'](arg1, arg2);
}

export function TogglePlugin(arg1, arg2) {
  return window['go']['main']['App']['TogglePlugin'](arg1, arg2);
}

export function ToggleResourceFavorite(arg1) {
  return window['go']['main']['App']['ToggleResourceFavorite'](arg1);
}

export function TriggerBackgroundRefresh() {
  return window['go']['main']['App']['TriggerBackgroundRefresh']();
}

export function UploadRemoteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadRemoteFile'](arg1, arg2, arg3);
}
