// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AskAICopilot(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function DeleteHost(arg1:string):Promise<void>;

export function GetActiveTunnels():Promise<Array<models.PortForwardRule>>;

export function GetHosts():Promise<Array<models.Host>>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveHost(arg1:models.Host):Promise<void>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<void>;

export function StartLocalTerminal(arg1:number,arg2:number):Promise<string>;

export function StartPortForward(arg1:string,arg2:models.PortForwardRule):Promise<void>;

export function StartSSHTerminal(arg1:string,arg2:number,arg3:number):Promise<string>;

export function StopPortForward(arg1:string):Promise<void>;
